In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import numpy as np
import pandas as pd
import random
import seaborn as sns
sns.set(style="ticks", color_codes=True)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import timeit

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [3]:
 #Loading Data set
KDD_Data = pd.read_csv("/content/drive/My Drive/NSL KDD/kddcup.data.corrected")

In [4]:
KDD_Data

         0  tcp  http  SF  215  ...  0.00.10  0.00.11  0.00.12  0.00.13  normal.
0        0  tcp  http  SF  162  ...      0.0     0.00      0.0      0.0  normal.
1        0  tcp  http  SF  236  ...      0.0     0.00      0.0      0.0  normal.
2        0  tcp  http  SF  233  ...      0.0     0.00      0.0      0.0  normal.
3        0  tcp  http  SF  239  ...      0.0     0.00      0.0      0.0  normal.
4        0  tcp  http  SF  238  ...      0.0     0.00      0.0      0.0  normal.
...     ..  ...   ...  ..  ...  ...      ...      ...      ...      ...      ...
4898425  0  tcp  http  SF  212  ...      0.0     0.01      0.0      0.0  normal.
4898426  0  tcp  http  SF  219  ...      0.0     0.01      0.0      0.0  normal.
4898427  0  tcp  http  SF  218  ...      0.0     0.01      0.0      0.0  normal.
4898428  0  tcp  http  SF  219  ...      0.0     0.01      0.0      0.0  normal.
4898429  0  tcp  http  SF  219  ...      0.0     0.01      0.0      0.0  normal.

[4898430 rows x 42 columns]

In [5]:
KDD_Data.iloc[:,41].unique()

array(['normal.', 'buffer_overflow.', 'loadmodule.', 'perl.', 'neptune.',
       'smurf.', 'guess_passwd.', 'pod.', 'teardrop.', 'portsweep.',
       'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.', 'satan.',
       'phf.', 'nmap.', 'multihop.', 'warezmaster.', 'warezclient.',
       'spy.', 'rootkit.'], dtype=object)

In [6]:
#shape of Data
KDD_Data.shape

(4898430, 42)

In [7]:
#Naming the columns
col=['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins',
  'logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files',
  'num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate',
  'same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate',
  'dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate',
  'dst_host_rerror_rate','dst_host_srv_rerror_rate','target']
KDD_Data.columns=col
KDD_Data.head(20)

    duration protocol_type  ... dst_host_srv_rerror_rate   target
0          0           tcp  ...                      0.0  normal.
1          0           tcp  ...                      0.0  normal.
2          0           tcp  ...                      0.0  normal.
3          0           tcp  ...                      0.0  normal.
4          0           tcp  ...                      0.0  normal.
5          0           tcp  ...                      0.0  normal.
6          0           tcp  ...                      0.0  normal.
7          0           tcp  ...                      0.0  normal.
8          0           tcp  ...                      0.0  normal.
9          0           tcp  ...                      0.0  normal.
10         0           tcp  ...                      0.0  normal.
11         0           tcp  ...                      0.0  normal.
12         0           tcp  ...                      0.0  normal.
13         0           tcp  ...                      0.0  normal.
14         0           tcp  ...                      0.0  normal.
15         0           tcp  ...                      0.0  normal.
16         0           tcp  ...                      0.0  normal.
17         0           tcp  ...                      0.0  normal.
18         0           tcp  ...                      0.0  normal.
19         0           tcp  ...                      0.0  normal.

[20 rows x 42 columns]

In [8]:
KDD_Data.shape

(4898430, 42)

In [9]:
#droping unnecessary columns
df = KDD_Data
df

         duration protocol_type  ... dst_host_srv_rerror_rate   target
0               0           tcp  ...                      0.0  normal.
1               0           tcp  ...                      0.0  normal.
2               0           tcp  ...                      0.0  normal.
3               0           tcp  ...                      0.0  normal.
4               0           tcp  ...                      0.0  normal.
...           ...           ...  ...                      ...      ...
4898425         0           tcp  ...                      0.0  normal.
4898426         0           tcp  ...                      0.0  normal.
4898427         0           tcp  ...                      0.0  normal.
4898428         0           tcp  ...                      0.0  normal.
4898429         0           tcp  ...                      0.0  normal.

[4898430 rows x 42 columns]

In [10]:
print(df.dtypes)

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
target                          object
dtype: object

In [11]:
from sklearn import preprocessing
#protocol_type
protocol_type = preprocessing.LabelEncoder()
protocol_type.fit(df['protocol_type'])
df['protocol_type']=protocol_type.transform(df['protocol_type'])
#service
service = preprocessing.LabelEncoder()
service.fit(df['service'])
df['service']=service.transform(df['service'])
# flag
service = preprocessing.LabelEncoder()
service.fit(df['flag'])
df['flag']=service.transform(df['flag'])
# target
service = preprocessing.LabelEncoder()
service.fit(df['target'])
df['target']=service.transform(df['target'])

In [12]:
 df.head(20)

    duration  protocol_type  ...  dst_host_srv_rerror_rate  target
0          0              1  ...                       0.0      11
1          0              1  ...                       0.0      11
2          0              1  ...                       0.0      11
3          0              1  ...                       0.0      11
4          0              1  ...                       0.0      11
5          0              1  ...                       0.0      11
6          0              1  ...                       0.0      11
7          0              1  ...                       0.0      11
8          0              1  ...                       0.0      11
9          0              1  ...                       0.0      11
10         0              1  ...                       0.0      11
11         0              1  ...                       0.0      11
12         0              1  ...                       0.0      11
13         0              1  ...                       0.0      11
14         0              1  ...                       0.0      11
15         0              1  ...                       0.0      11
16         0              1  ...                       0.0      11
17         0              1  ...                       0.0      11
18         0              1  ...                       0.0      11
19         0              1  ...                       0.0      11

[20 rows x 42 columns]

In [13]:
 D=['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins',
  'logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files',
  'num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate',
  'same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate',
  'dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate',
  'dst_host_rerror_rate','dst_host_srv_rerror_rate']
X=df[D]
y=df['target']

In [14]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
#selecting 10 best features
best= SelectKBest(chi2, k=10)
X_new=best.fit_transform(X, y)
X_new.shape

(4898430, 10)

In [15]:
mask = best.get_support() #list of booleans
new_features = [] # The list of your K best features

for bool, feature in zip(mask, D):
    if bool:
        new_features.append(feature)

In [16]:
new_features

['duration',
 'service',
 'src_bytes',
 'dst_bytes',
 'wrong_fragment',
 'hot',
 'count',
 'srv_count',
 'dst_host_count',
 'dst_host_srv_count']

In [17]:
X_feat=pd.DataFrame(X_new,columns=new_features)
X_feat

         duration  service  ...  dst_host_count  dst_host_srv_count
0             0.0     24.0  ...             1.0                 1.0
1             0.0     24.0  ...             2.0                 2.0
2             0.0     24.0  ...             3.0                 3.0
3             0.0     24.0  ...             4.0                 4.0
4             0.0     24.0  ...             5.0                 5.0
...           ...      ...  ...             ...                 ...
4898425       0.0     24.0  ...             3.0               255.0
4898426       0.0     24.0  ...             4.0               255.0
4898427       0.0     24.0  ...             5.0               255.0
4898428       0.0     24.0  ...             6.0               255.0
4898429       0.0     24.0  ...             7.0               255.0

[4898430 rows x 10 columns]

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_feat_scaled=scaler.fit_transform(X_feat)

In [19]:
X_feat_scaled

array([[-6.68331923e-02, -8.88374628e-02, -1.77667973e-03, ...,
        -1.19217837e+00, -3.62352464e+00, -1.77706947e+00],
       [-6.68331923e-02, -8.88374628e-02, -1.69807599e-03, ...,
        -1.19624353e+00, -3.60790473e+00, -1.76762773e+00],
       [-6.68331923e-02, -8.88374628e-02, -1.70126263e-03, ...,
        -1.19217837e+00, -3.59228482e+00, -1.75818599e+00],
       ...,
       [-6.68331923e-02, -8.88374628e-02, -1.71719582e-03, ...,
        -1.06209320e+00, -3.56104499e+00,  6.21131328e-01],
       [-6.68331923e-02, -8.88374628e-02, -1.71613361e-03, ...,
        -1.05802804e+00, -3.54542508e+00,  6.21131328e-01],
       [-6.68331923e-02, -8.88374628e-02, -1.71613361e-03, ...,
        -1.19624353e+00, -3.52980517e+00,  6.21131328e-01]])

In [20]:
ran = 42
X_train, X_test, y_train, y_test = train_test_split(X_feat_scaled, y, test_size=0.2, random_state = ran)

In [21]:
from __future__ import print_function
# from sklearn.cross_validation import train_test_split
import pandas as pd
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Embedding
from keras.layers import LSTM, SimpleRNN, GRU
from keras.datasets import imdb
from keras.utils.np_utils import to_categorical
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn import metrics
from sklearn.preprocessing import Normalizer
import h5py
from keras import callbacks
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

Using TensorFlow backend.

In [22]:
y_train1 = np.array(y_train)
y_test1 = np.array(y_test)

y_train= to_categorical(y_train1)
y_test= to_categorical(y_test1)

X_train = np.array(X_train)
X_test = np.array(X_test)

In [23]:
batch_size = 64

# 1. define the network
model = Sequential()
model.add(Dense(1024,input_dim=10,activation='relu'))  
model.add(Dropout(0.01))
model.add(Dense(768,activation='relu'))  
model.add(Dropout(0.01))
model.add(Dense(512,activation='relu'))  
model.add(Dropout(0.01))
model.add(Dense(256,activation='relu'))  
model.add(Dropout(0.01))
model.add(Dense(128,activation='relu'))  
model.add(Dropout(0.01))
model.add(Dense(23))
model.add(Activation('softmax'))
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto',
      restore_best_weights=True)

In [ ]:
# try using different optimizers and different optimizer configs
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test),batch_size=batch_size, nb_epoch=10,callbacks=[monitor])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until

Train on 3918744 samples, validate on 979686 samples
Epoch 1/10
3918744/3918744 [==============================] - 623s 159us/step - loss: 0.0200 - accuracy: 0.9950 - val_loss: 0.0163 - val_accuracy: 0.9957
Epoch 2/10
 170752/3918744 [>.............................] - ETA: 9:08 - loss: 0.0166 - accuracy: 0.9959

In [ ]:
#model2
batch_size = 64

# 1. define the network
model2 = Sequential()
model2.add(Dense(1024,input_dim=10,activation='relu'))  
model2.add(Dropout(0.01))
model2.add(Dense(23))
model2.add(Activation('softmax'))
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto',
      restore_best_weights=True)

In [ ]:
# try using different optimizers and different optimizer configs
model2.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])
model2.fit(X_train, y_train, validation_data=(X_test, y_test),batch_size=batch_size, nb_epoch=10,callbacks=[monitor])