In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import random
import seaborn as sns
sns.set(style="ticks", color_codes=True)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import timeit

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
 #Loading Data set
KDD_Data = pd.read_csv("/content/drive/My Drive/NSL KDD/kddcup.data.corrected")

In [ ]:
KDD_Data

         0  tcp  http  SF  215  ...  0.00.10  0.00.11  0.00.12  0.00.13  normal.
0        0  tcp  http  SF  162  ...      0.0     0.00      0.0      0.0  normal.
1        0  tcp  http  SF  236  ...      0.0     0.00      0.0      0.0  normal.
2        0  tcp  http  SF  233  ...      0.0     0.00      0.0      0.0  normal.
3        0  tcp  http  SF  239  ...      0.0     0.00      0.0      0.0  normal.
4        0  tcp  http  SF  238  ...      0.0     0.00      0.0      0.0  normal.
...     ..  ...   ...  ..  ...  ...      ...      ...      ...      ...      ...
4898425  0  tcp  http  SF  212  ...      0.0     0.01      0.0      0.0  normal.
4898426  0  tcp  http  SF  219  ...      0.0     0.01      0.0      0.0  normal.
4898427  0  tcp  http  SF  218  ...      0.0     0.01      0.0      0.0  normal.
4898428  0  tcp  http  SF  219  ...      0.0     0.01      0.0      0.0  normal.
4898429  0  tcp  http  SF  219  ...      0.0     0.01      0.0      0.0  normal.

[4898430 rows x 42 columns]

In [ ]:
KDD_Data.iloc[:,41].unique()

array(['normal.', 'buffer_overflow.', 'loadmodule.', 'perl.', 'neptune.',
       'smurf.', 'guess_passwd.', 'pod.', 'teardrop.', 'portsweep.',
       'ipsweep.', 'land.', 'ftp_write.', 'back.', 'imap.', 'satan.',
       'phf.', 'nmap.', 'multihop.', 'warezmaster.', 'warezclient.',
       'spy.', 'rootkit.'], dtype=object)

In [ ]:
#shape of Data
KDD_Data.shape

(4898430, 42)

In [ ]:
#Naming the columns
col=['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins',
  'logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files',
  'num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate',
  'same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate',
  'dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate',
  'dst_host_rerror_rate','dst_host_srv_rerror_rate','target']
KDD_Data.columns=col
KDD_Data.head(20)

    duration protocol_type  ... dst_host_srv_rerror_rate   target
0          0           tcp  ...                      0.0  normal.
1          0           tcp  ...                      0.0  normal.
2          0           tcp  ...                      0.0  normal.
3          0           tcp  ...                      0.0  normal.
4          0           tcp  ...                      0.0  normal.
5          0           tcp  ...                      0.0  normal.
6          0           tcp  ...                      0.0  normal.
7          0           tcp  ...                      0.0  normal.
8          0           tcp  ...                      0.0  normal.
9          0           tcp  ...                      0.0  normal.
10         0           tcp  ...                      0.0  normal.
11         0           tcp  ...                      0.0  normal.
12         0           tcp  ...                      0.0  normal.
13         0           tcp  ...                      0.0  normal.
14         0           tcp  ...                      0.0  normal.
15         0           tcp  ...                      0.0  normal.
16         0           tcp  ...                      0.0  normal.
17         0           tcp  ...                      0.0  normal.
18         0           tcp  ...                      0.0  normal.
19         0           tcp  ...                      0.0  normal.

[20 rows x 42 columns]

In [ ]:
KDD_Data.shape

(4898430, 42)

In [ ]:
#droping unnecessary columns
df = KDD_Data
df

         duration protocol_type  ... dst_host_srv_rerror_rate   target
0               0           tcp  ...                      0.0  normal.
1               0           tcp  ...                      0.0  normal.
2               0           tcp  ...                      0.0  normal.
3               0           tcp  ...                      0.0  normal.
4               0           tcp  ...                      0.0  normal.
...           ...           ...  ...                      ...      ...
4898425         0           tcp  ...                      0.0  normal.
4898426         0           tcp  ...                      0.0  normal.
4898427         0           tcp  ...                      0.0  normal.
4898428         0           tcp  ...                      0.0  normal.
4898429         0           tcp  ...                      0.0  normal.

[4898430 rows x 42 columns]

In [ ]:
print(df.dtypes)

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
target                          object
dtype: object

In [ ]:
from sklearn import preprocessing
#protocol_type
protocol_type = preprocessing.LabelEncoder()
protocol_type.fit(df['protocol_type'])
df['protocol_type']=protocol_type.transform(df['protocol_type'])
#service
service = preprocessing.LabelEncoder()
service.fit(df['service'])
df['service']=service.transform(df['service'])
# flag
service = preprocessing.LabelEncoder()
service.fit(df['flag'])
df['flag']=service.transform(df['flag'])
# target
service = preprocessing.LabelEncoder()
service.fit(df['target'])
df['target']=service.transform(df['target'])

In [ ]:
 df.head(20)

    duration  protocol_type  ...  dst_host_srv_rerror_rate  target
0          0              1  ...                       0.0      11
1          0              1  ...                       0.0      11
2          0              1  ...                       0.0      11
3          0              1  ...                       0.0      11
4          0              1  ...                       0.0      11
5          0              1  ...                       0.0      11
6          0              1  ...                       0.0      11
7          0              1  ...                       0.0      11
8          0              1  ...                       0.0      11
9          0              1  ...                       0.0      11
10         0              1  ...                       0.0      11
11         0              1  ...                       0.0      11
12         0              1  ...                       0.0      11
13         0              1  ...                       0.0      11
14         0              1  ...                       0.0      11
15         0              1  ...                       0.0      11
16         0              1  ...                       0.0      11
17         0              1  ...                       0.0      11
18         0              1  ...                       0.0      11
19         0              1  ...                       0.0      11

[20 rows x 42 columns]

In [ ]:
 D=['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins',
  'logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files',
  'num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate',
  'same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate',
  'dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate',
  'dst_host_rerror_rate','dst_host_srv_rerror_rate']
X=df[D]
y=df['target']

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
#selecting 10 best features
best= SelectKBest(chi2, k=10)
X_new=best.fit_transform(X, y)
X_new.shape

(4898430, 10)

In [ ]:
mask = best.get_support() #list of booleans
new_features = [] # The list of your K best features

for bool, feature in zip(mask, D):
    if bool:
        new_features.append(feature)

In [ ]:
new_features

['duration',
 'service',
 'src_bytes',
 'dst_bytes',
 'wrong_fragment',
 'hot',
 'count',
 'srv_count',
 'dst_host_count',
 'dst_host_srv_count']

In [ ]:
X_feat=pd.DataFrame(X_new,columns=new_features)
X_feat

         duration  service  ...  dst_host_count  dst_host_srv_count
0             0.0     24.0  ...             1.0                 1.0
1             0.0     24.0  ...             2.0                 2.0
2             0.0     24.0  ...             3.0                 3.0
3             0.0     24.0  ...             4.0                 4.0
4             0.0     24.0  ...             5.0                 5.0
...           ...      ...  ...             ...                 ...
4898425       0.0     24.0  ...             3.0               255.0
4898426       0.0     24.0  ...             4.0               255.0
4898427       0.0     24.0  ...             5.0               255.0
4898428       0.0     24.0  ...             6.0               255.0
4898429       0.0     24.0  ...             7.0               255.0

[4898430 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_feat_scaled=scaler.fit_transform(X_feat)

In [ ]:
X_feat_scaled

array([[-6.68331923e-02, -8.88374628e-02, -1.77667973e-03, ...,
        -1.19217837e+00, -3.62352464e+00, -1.77706947e+00],
       [-6.68331923e-02, -8.88374628e-02, -1.69807599e-03, ...,
        -1.19624353e+00, -3.60790473e+00, -1.76762773e+00],
       [-6.68331923e-02, -8.88374628e-02, -1.70126263e-03, ...,
        -1.19217837e+00, -3.59228482e+00, -1.75818599e+00],
       ...,
       [-6.68331923e-02, -8.88374628e-02, -1.71719582e-03, ...,
        -1.06209320e+00, -3.56104499e+00,  6.21131328e-01],
       [-6.68331923e-02, -8.88374628e-02, -1.71613361e-03, ...,
        -1.05802804e+00, -3.54542508e+00,  6.21131328e-01],
       [-6.68331923e-02, -8.88374628e-02, -1.71613361e-03, ...,
        -1.19624353e+00, -3.52980517e+00,  6.21131328e-01]])

In [ ]:
ran = 42
X_train, X_test, y_train, y_test = train_test_split(X_feat_scaled, y, test_size=0.2, random_state = ran)

In [ ]:
from keras.layers import LSTM, SimpleRNN, GRU
from __future__ import print_function
# from sklearn.cross_validation import train_test_split
import pandas as pd
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Embedding
from keras.layers import LSTM, SimpleRNN, GRU
from keras.datasets import imdb
from keras.utils.np_utils import to_categorical
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn import metrics
from sklearn.preprocessing import Normalizer
import h5py
from keras import callbacks
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

Using TensorFlow backend.

In [ ]:
y_train1 = np.array(y_train)
y_test1 = np.array(y_test)

y_train= to_categorical(y_train1)
y_test= to_categorical(y_test1)

X_train = np.array(X_train)
X_test = np.array(X_test)

In [ ]:
X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0], 1, X_test.shape[1]))

In [ ]:
batch_size = 32

# 1. define the network
model = Sequential()
model.add(LSTM(40,input_dim=10, return_sequences=True))  # try using a GRU instead, for fun
model.add(Dropout(0.1))
model.add(LSTM(20,input_dim=10, return_sequences=False))  # try using a GRU instead, for fun
model.add(Dropout(0.1))
model.add(Dense(23))
model.add(Activation('softmax'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(40, return_sequences=True, input_shape=(None, 10))`
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(20, return_sequences=False, input_shape=(None, 10))`
  import sys

In [ ]:
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto',
      restore_best_weights=True)

In [ ]:
# try using different optimizers and different optimizer configs
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test),batch_size=batch_size, nb_epoch=20,callbacks=[monitor])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until

Train on 3918744 samples, validate on 979686 samples
Epoch 1/20
3918744/3918744 [==============================] - 358s 91us/step - loss: 0.0326 - accuracy: 0.9919 - val_loss: 0.0223 - val_accuracy: 0.9940
Epoch 2/20
3918744/3918744 [==============================] - 357s 91us/step - loss: 0.0225 - accuracy: 0.9946 - val_loss: 0.0192 - val_accuracy: 0.9950
Epoch 3/20
3918744/3918744 [==============================] - 362s 92us/step - loss: 0.0207 - accuracy: 0.9952 - val_loss: 0.0182 - val_accuracy: 0.9960
Epoch 4/20
3918744/3918744 [==============================] - 367s 94us/step - loss: 0.0196 - accuracy: 0.9956 - val_loss: 0.0175 - val_accuracy: 0.9957
Epoch 5/20
3918744/3918744 [==============================] - 364s 93us/step - loss: 0.0190 - accuracy: 0.9957 - val_loss: 0.0179 - val_accuracy: 0.9957
Epoch 6/20
3918744/3918744 [==============================] - 370s 94us/step - loss: 0.0192 - accuracy: 0.9957 - val_loss: 0.0161 - val_accuracy: 0.9967
Epoch 7/20
3918744/3918744 [==============================] - 372s 95us/step - loss: 0.0189 - accuracy: 0.9957 - val_loss: 0.0161 - val_accuracy: 0.9965
Epoch 8/20
3918744/3918744 [==============================] - 377s 96us/step - loss: 0.0189 - accuracy: 0.9958 - val_loss: 0.0160 - val_accuracy: 0.9967
Epoch 9/20
3918744/3918744 [==============================] - 378s 96us/step - loss: 0.0187 - accuracy: 0.9958 - val_loss: 0.0157 - val_accuracy: 0.9967
Epoch 10/20
3300096/3918744 [========================>.....] - ETA: 54s - loss: 0.0185 - accuracy: 0.9959

In [ ]:
pred_LSTM=model.predict_classes(X_test)

In [ ]:
from sklearn.metrics import classification_report
# target_names = ['0', 'class 1', 'class 2','class 3','class 4']
print(classification_report(service.inverse_transform(y_test1), service.inverse_transform(pred_LSTM)))