In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import random
import seaborn as sns
sns.set(style="ticks", color_codes=True)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import timeit
from tensorflow.keras.callbacks import EarlyStopping

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [3]:
 #Loading Data set
NSL_Data = pd.read_csv("/content/drive/My Drive/NSL KDD/KDDTrain+.txt")

In [4]:
NSL_Data

        0  tcp  ftp_data   SF   491  ...  0.00.8  0.05  0.00.9   normal  20
0       0  udp     other   SF   146  ...    0.00  0.00    0.00   normal  15
1       0  tcp   private   S0     0  ...    1.00  0.00    0.00  neptune  19
2       0  tcp      http   SF   232  ...    0.01  0.00    0.01   normal  21
3       0  tcp      http   SF   199  ...    0.00  0.00    0.00   normal  21
4       0  tcp   private  REJ     0  ...    0.00  1.00    1.00  neptune  21
...    ..  ...       ...  ...   ...  ...     ...   ...     ...      ...  ..
125967  0  tcp   private   S0     0  ...    1.00  0.00    0.00  neptune  20
125968  8  udp   private   SF   105  ...    0.00  0.00    0.00   normal  21
125969  0  tcp      smtp   SF  2231  ...    0.00  0.01    0.00   normal  18
125970  0  tcp    klogin   S0     0  ...    1.00  0.00    0.00  neptune  20
125971  0  tcp  ftp_data   SF   151  ...    0.00  0.00    0.00   normal  21

[125972 rows x 43 columns]

In [5]:
NSL_Data.iloc[:,41].unique()

array(['normal', 'neptune', 'warezclient', 'ipsweep', 'portsweep',
       'teardrop', 'nmap', 'satan', 'smurf', 'pod', 'back',
       'guess_passwd', 'ftp_write', 'multihop', 'rootkit',
       'buffer_overflow', 'imap', 'warezmaster', 'phf', 'land',
       'loadmodule', 'spy', 'perl'], dtype=object)

In [6]:
#shape of Data
NSL_Data.shape

(125972, 43)

In [7]:
#Naming the columns
col=['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins',
  'logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files',
  'num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate',
  'same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate',
  'dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate',
  'dst_host_rerror_rate','dst_host_srv_rerror_rate','target','lrn']
NSL_Data.columns=col
NSL_Data.head(20)

    duration protocol_type  ...       target lrn
0          0           udp  ...       normal  15
1          0           tcp  ...      neptune  19
2          0           tcp  ...       normal  21
3          0           tcp  ...       normal  21
4          0           tcp  ...      neptune  21
5          0           tcp  ...      neptune  21
6          0           tcp  ...      neptune  21
7          0           tcp  ...      neptune  21
8          0           tcp  ...      neptune  21
9          0           tcp  ...      neptune  21
10         0           tcp  ...      neptune  21
11         0           tcp  ...       normal  21
12         0           tcp  ...  warezclient  15
13         0           tcp  ...      neptune  19
14         0           tcp  ...      neptune  18
15         0           tcp  ...       normal  21
16         0          icmp  ...      ipsweep  18
17         0           tcp  ...       normal  21
18         0           tcp  ...       normal  21
19         0           tcp  ...      neptune  18

[20 rows x 43 columns]

In [8]:
NSL_Data.shape

(125972, 43)

In [9]:
#droping unnecessary columns
df = NSL_Data.drop('lrn',axis=1)
df

        duration protocol_type  ... dst_host_srv_rerror_rate   target
0              0           udp  ...                     0.00   normal
1              0           tcp  ...                     0.00  neptune
2              0           tcp  ...                     0.01   normal
3              0           tcp  ...                     0.00   normal
4              0           tcp  ...                     1.00  neptune
...          ...           ...  ...                      ...      ...
125967         0           tcp  ...                     0.00  neptune
125968         8           udp  ...                     0.00   normal
125969         0           tcp  ...                     0.00   normal
125970         0           tcp  ...                     0.00  neptune
125971         0           tcp  ...                     0.00   normal

[125972 rows x 42 columns]

In [10]:
print(df.dtypes)

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate                float64
rerror_rate                    float64
srv_rerror_rate                float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_srv_count               int64
dst_host_same_srv_rate         float64
dst_host_diff_srv_rate         float64
dst_host_same_src_port_rate    float64
dst_host_srv_diff_host_rate    float64
dst_host_serror_rate           float64
dst_host_srv_serror_rate       float64
dst_host_rerror_rate           float64
dst_host_srv_rerror_rate       float64
target                          object
dtype: object

In [11]:
from sklearn import preprocessing
#protocol_type
protocol_type = preprocessing.LabelEncoder()
protocol_type.fit(df['protocol_type'])
df['protocol_type']=protocol_type.transform(df['protocol_type'])
#service
service = preprocessing.LabelEncoder()
service.fit(df['service'])
df['service']=service.transform(df['service'])
# flag
service = preprocessing.LabelEncoder()
service.fit(df['flag'])
df['flag']=service.transform(df['flag'])
# target
service = preprocessing.LabelEncoder()
service.fit(df['target'])
df['target']=service.transform(df['target'])

In [12]:
 df.head(20)

    duration  protocol_type  ...  dst_host_srv_rerror_rate  target
0          0              2  ...                      0.00      11
1          0              1  ...                      0.00       9
2          0              1  ...                      0.01      11
3          0              1  ...                      0.00      11
4          0              1  ...                      1.00       9
5          0              1  ...                      0.00       9
6          0              1  ...                      0.00       9
7          0              1  ...                      0.00       9
8          0              1  ...                      0.00       9
9          0              1  ...                      1.00       9
10         0              1  ...                      0.00       9
11         0              1  ...                      0.00      11
12         0              1  ...                      0.00      21
13         0              1  ...                      0.00       9
14         0              1  ...                      0.00       9
15         0              1  ...                      0.00      11
16         0              0  ...                      0.00       5
17         0              1  ...                      0.00      11
18         0              1  ...                      0.00      11
19         0              1  ...                      0.00       9

[20 rows x 42 columns]

In [13]:
 D=['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins',
  'logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files',
  'num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate',
  'same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate',
  'dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate',
  'dst_host_rerror_rate','dst_host_srv_rerror_rate']
X=df[D]
y=df['target']

In [14]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
#selecting 10 best features
best= SelectKBest(chi2, k=10)
X_new=best.fit_transform(X, y)
X_new.shape

(125972, 10)

In [15]:
mask = best.get_support() #list of booleans
new_features = [] # The list of your K best features

for bool, feature in zip(mask, D):
    if bool:
        new_features.append(feature)

In [16]:
new_features

['duration',
 'service',
 'src_bytes',
 'dst_bytes',
 'wrong_fragment',
 'hot',
 'count',
 'srv_count',
 'dst_host_count',
 'dst_host_srv_count']

In [17]:
X_feat=pd.DataFrame(X_new,columns=new_features)
X_feat

        duration  service  ...  dst_host_count  dst_host_srv_count
0            0.0     44.0  ...           255.0                 1.0
1            0.0     49.0  ...           255.0                26.0
2            0.0     24.0  ...            30.0               255.0
3            0.0     24.0  ...           255.0               255.0
4            0.0     49.0  ...           255.0                19.0
...          ...      ...  ...             ...                 ...
125967       0.0     49.0  ...           255.0                25.0
125968       8.0     49.0  ...           255.0               244.0
125969       0.0     54.0  ...           255.0                30.0
125970       0.0     30.0  ...           255.0                 8.0
125971       0.0     20.0  ...           255.0                77.0

[125972 rows x 10 columns]

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_feat_scaled=scaler.fit_transform(X_feat)

In [19]:
X_feat_scaled

array([[-0.11024967,  0.78142044, -0.0077374 , ..., -0.36811175,
         0.73433738, -1.03569278],
       [-0.11024967,  1.08729745, -0.00776227, ..., -0.29927517,
         0.73433738, -0.80986218],
       [-0.11024967, -0.44208761, -0.00772275, ..., -0.31304249,
        -1.53366668,  1.25874613],
       ...,
       [-0.11024967,  1.39317446, -0.00738222, ..., -0.36811175,
         0.73433738, -0.77372929],
       [-0.11024967, -0.0750352 , -0.00776227, ..., -0.27174054,
         0.73433738, -0.97246022],
       [-0.11024967, -0.68678922, -0.00773655, ..., -0.36811175,
         0.73433738, -0.34916776]])

In [20]:
ran = 42
X_train, X_test, y_train, y_test = train_test_split(X_feat_scaled, y, test_size=0.2, random_state = ran)

In [21]:
from keras.layers import LSTM, SimpleRNN, GRU
from __future__ import print_function
# from sklearn.cross_validation import train_test_split
import pandas as pd
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Embedding
from keras.layers import LSTM, SimpleRNN, GRU
from keras.datasets import imdb
from keras.utils.np_utils import to_categorical
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn import metrics
from sklearn.preprocessing import Normalizer
import h5py
from keras import callbacks
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

Using TensorFlow backend.

In [22]:
y_train1 = np.array(y_train)
y_test1 = np.array(y_test)

y_train= to_categorical(y_train1)
y_test= to_categorical(y_test1)

X_train = np.array(X_train)
X_test = np.array(X_test)

In [29]:
X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0], 1, X_test.shape[1]))

In [33]:
batch_size = 32

# 1. define the network
model = Sequential()
model.add(LSTM(8,input_dim=10, return_sequences=True))  # try using a GRU instead, for fun
model.add(Dropout(0.1))
model.add(LSTM(8,input_dim=10, return_sequences=False))  # try using a GRU instead, for fun
model.add(Dropout(0.1))
model.add(Dense(23))
model.add(Activation('softmax'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(8, return_sequences=True, input_shape=(None, 10))`
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(8, return_sequences=False, input_shape=(None, 10))`
  import sys

In [34]:
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto',
      restore_best_weights=True)

In [35]:
# try using different optimizers and different optimizer configs
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test),batch_size=batch_size, nb_epoch=10,callbacks=[monitor])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  This is separate from the ipykernel package so we can avoid doing imports until

Train on 100777 samples, validate on 25195 samples
Epoch 1/10
100777/100777 [==============================] - 10s 96us/step - loss: 0.6256 - accuracy: 0.8476 - val_loss: 0.4331 - val_accuracy: 0.8843
Epoch 2/10
100777/100777 [==============================] - 9s 86us/step - loss: 0.4292 - accuracy: 0.8840 - val_loss: 0.3765 - val_accuracy: 0.8918
Epoch 3/10
100777/100777 [==============================] - 9s 86us/step - loss: 0.3933 - accuracy: 0.8891 - val_loss: 0.3524 - val_accuracy: 0.8979
Epoch 4/10
100777/100777 [==============================] - 9s 87us/step - loss: 0.3713 - accuracy: 0.8944 - val_loss: 0.3313 - val_accuracy: 0.9008
Epoch 5/10
100777/100777 [==============================] - 9s 85us/step - loss: 0.3488 - accuracy: 0.8970 - val_loss: 0.3084 - val_accuracy: 0.9045
Epoch 6/10
100777/100777 [==============================] - 9s 87us/step - loss: 0.3298 - accuracy: 0.9046 - val_loss: 0.2935 - val_accuracy: 0.9146
Epoch 7/10
100777/100777 [==============================] - 9s 86us/step - loss: 0.3226 - accuracy: 0.9064 - val_loss: 0.2841 - val_accuracy: 0.9143
Epoch 8/10
100777/100777 [==============================] - 9s 86us/step - loss: 0.3131 - accuracy: 0.9083 - val_loss: 0.2768 - val_accuracy: 0.9155
Epoch 9/10
100777/100777 [==============================] - 9s 86us/step - loss: 0.3079 - accuracy: 0.9089 - val_loss: 0.2675 - val_accuracy: 0.9224
Epoch 10/10
100777/100777 [==============================] - 9s 88us/step - loss: 0.3008 - accuracy: 0.9104 - val_loss: 0.2617 - val_accuracy: 0.9232

In [37]:
pred_LSTM=model.predict_classes(X_test)

In [38]:
from sklearn.metrics import classification_report
# target_names = ['0', 'class 1', 'class 2','class 3','class 4']
print(classification_report(service.inverse_transform(y_test1), service.inverse_transform(pred_LSTM)))

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

                 precision    recall  f1-score   support

           back       0.86      0.93      0.89       201
buffer_overflow       0.00      0.00      0.00         7
   guess_passwd       0.00      0.00      0.00        14
           imap       0.00      0.00      0.00         2
        ipsweep       0.70      0.89      0.79       743
           land       0.00      0.00      0.00         2
     loadmodule       0.00      0.00      0.00         3
       multihop       0.00      0.00      0.00         1
        neptune       0.95      0.97      0.96      8238
           nmap       0.00      0.00      0.00       298
         normal       0.93      0.98      0.96     13386
           perl       0.00      0.00      0.00         1
            phf       0.00      0.00      0.00         1
            pod       1.00      0.97      0.99        36
      portsweep       0.82      0.55      0.66       583
        rootkit       0.00      0.00      0.00         2
          satan       0.77      0.50      0.60       749
          smurf       1.00      0.67      0.80       551
            spy       0.00      0.00      0.00         1
       teardrop       1.00      1.00      1.00       196
    warezclient       0.00      0.00      0.00       176
    warezmaster       0.00      0.00      0.00         4

       accuracy                           0.92     25195
      macro avg       0.36      0.34      0.35     25195
   weighted avg       0.90      0.92      0.91     25195